#SPDX-License-Identifier: MIT-0
---
# defaults file for docker

docker_packages:
  - docker-ce
  - docker-ce-cli
  - containerd.io
  - docker-compose-plugin

docker_apt_repo_uri: https://download.docker.com/linux/debian
docker_apt_gpg_key_url: https://download.docker.com/linux/debian/gpg

docker_add_user_to_group: true
docker_group_user: debian
